/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supertankbattle;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {
    //Declaraciones
    private Tank jugador;
    private Graphics g;
    private Recursos rec;
    final private int ventanaAncho = 800;
    final private int ventanaAlto = 640;
    final private int FPS = 120;
    /**
     * Creates new form Menu
     */
    public Principal() {
        initComponents();
        this.setResizable(false);
        this.setSize(ventanaAncho, ventanaAlto);
        g=ventanaMenu.getGraphics();
        ventanaMenu.setFocusable(true);
        try{
        rec = new Recursos();
        jugador = new Tank(2,this.getWidth()/2,this.getHeight()/2,0,rec.getImg_tanques()[2][0]);
        drawTanks();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Ocurrio un error de tipo: "+ex.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
        }
        

        
    }
    
    public void drawTanks() throws IOException
    {
        Thread game = new Thread(){
        @Override
        public void run() {
            while (true) {
               // Execute one time-step for the game 
               g = ventanaMenu.getGraphics();
               jugador.draw(g);
               
               //update
               ventanaMenu.repaint();
               
               // Delay and give other thread a chance
               try {
                  Thread.sleep(1000/FPS);
               } catch (InterruptedException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Ocurrio un error de tipo: "+ex.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
               }
            }
         }
      };
        game.start();
        
    }
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Tank Battle");

        ventanaMenu.setBackground(new java.awt.Color(0, 51, 51));
        ventanaMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ventanaMenuKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout ventanaMenuLayout = new javax.swing.GroupLayout(ventanaMenu);
        ventanaMenu.setLayout(ventanaMenuLayout);
        ventanaMenuLayout.setHorizontalGroup(
            ventanaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ventanaMenuLayout.setVerticalGroup(
            ventanaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventanaMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ventanaMenuKeyPressed
        int keycode = evt.getKeyCode();
        try{
            switch (keycode){
                case java.awt.event.KeyEvent.VK_UP:
                    jugador.move_up(0);
                    break;
                case java.awt.event.KeyEvent.VK_LEFT:
                    jugador.move_left(0);
                    break;
                case java.awt.event.KeyEvent.VK_RIGHT:
                    jugador.move_right(ventanaAncho);
                    break;
                case java.awt.event.KeyEvent.VK_DOWN:
                    jugador.move_down(ventanaAlto);
                    break;
                case java.awt.event.KeyEvent.VK_SPACE:
                    jugador.shoot(ventanaMenu.getGraphics());
                    break;
            }
            jugador.setImage(rec.getImg_tanques()[jugador.getTipo()][jugador.getDirection()]);
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Ocurrio un error de tipo: "+ex.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
        }
        
    
    }//GEN-LAST:event_ventanaMenuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ventanaMenu;
    // End of variables declaration//GEN-END:variables
}
